@startuml
!define RECTANGLE class
skinparam class {
  BackgroundColor White
  ArrowColor Black
  BorderColor Black
}

RECTANGLE "Cadastrar Carro" as A1
RECTANGLE "Listar Carros" as A2
RECTANGLE "Editar Carro" as A3
RECTANGLE "Remover Carro" as A4

A1 -down-> A2
A2 -down-> A3
A3 -down-> A4
@enduml
